/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class Layanan extends javax.swing.JFrame {

    /**
     * Creates new form Layanan
     */
    public Layanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        akunButton = new javax.swing.JButton();
        riwayatButton = new javax.swing.JButton();
        riwayatButton1 = new javax.swing.JButton();
        riwayatButton2 = new javax.swing.JButton();
        statusButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        statusButton2 = new javax.swing.JButton();
        statusButton3 = new javax.swing.JButton();
        statusButton4 = new javax.swing.JButton();
        statusButton5 = new javax.swing.JButton();
        statusButton6 = new javax.swing.JButton();
        statusButton7 = new javax.swing.JButton();
        statusButton8 = new javax.swing.JButton();
        statusButton9 = new javax.swing.JButton();
        statusButton10 = new javax.swing.JButton();
        statusButton11 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        statusButton12 = new javax.swing.JButton();
        statusButton13 = new javax.swing.JButton();
        statusButton14 = new javax.swing.JButton();
        statusButton15 = new javax.swing.JButton();
        statusButton16 = new javax.swing.JButton();
        statusButton17 = new javax.swing.JButton();
        statusButton18 = new javax.swing.JButton();
        statusButton19 = new javax.swing.JButton();
        statusButton20 = new javax.swing.JButton();
        statusButton21 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        statusButton32 = new javax.swing.JButton();
        statusButton33 = new javax.swing.JButton();
        statusButton34 = new javax.swing.JButton();
        statusButton35 = new javax.swing.JButton();
        statusButton36 = new javax.swing.JButton();
        statusButton37 = new javax.swing.JButton();
        statusButton38 = new javax.swing.JButton();
        statusButton39 = new javax.swing.JButton();
        statusButton40 = new javax.swing.JButton();
        statusButton41 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 0));

        jPanel4.setBackground(new java.awt.Color(42, 97, 153));

        jLabel7.setBackground(new java.awt.Color(0, 50, 133));
        jLabel7.setFont(new java.awt.Font("Poppins ExtraBold", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Paket Gold");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(42, 98, 154));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        akunButton.setBackground(new java.awt.Color(42, 98, 154));
        akunButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        akunButton.setForeground(new java.awt.Color(255, 255, 255));
        akunButton.setText("Layanan");
        akunButton.setAlignmentY(1.0F);
        akunButton.setBorderPainted(false);
        akunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akunButtonActionPerformed(evt);
            }
        });
        jPanel2.add(akunButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 90, 20));

        riwayatButton.setBackground(new java.awt.Color(42, 98, 154));
        riwayatButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        riwayatButton.setForeground(new java.awt.Color(255, 255, 255));
        riwayatButton.setText("Riwayat");
        riwayatButton.setAlignmentY(1.0F);
        riwayatButton.setBorderPainted(false);
        riwayatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatButtonActionPerformed(evt);
            }
        });
        jPanel2.add(riwayatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, 20));

        riwayatButton1.setBackground(new java.awt.Color(42, 98, 154));
        riwayatButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        riwayatButton1.setForeground(new java.awt.Color(255, 255, 255));
        riwayatButton1.setText("Pesan");
        riwayatButton1.setAlignmentY(1.0F);
        riwayatButton1.setBorderPainted(false);
        riwayatButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(riwayatButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, 20));

        riwayatButton2.setBackground(new java.awt.Color(42, 98, 154));
        riwayatButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        riwayatButton2.setForeground(new java.awt.Color(255, 255, 255));
        riwayatButton2.setText("Kontak");
        riwayatButton2.setAlignmentY(1.0F);
        riwayatButton2.setBorderPainted(false);
        riwayatButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(riwayatButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 20));

        statusButton1.setBackground(new java.awt.Color(42, 98, 154));
        statusButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        statusButton1.setForeground(new java.awt.Color(255, 255, 255));
        statusButton1.setText("Beranda");
        statusButton1.setAlignmentY(1.0F);
        statusButton1.setBorderPainted(false);
        statusButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(statusButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel9.setBackground(new java.awt.Color(42, 97, 153));

        jLabel17.setBackground(new java.awt.Color(0, 50, 133));
        jLabel17.setFont(new java.awt.Font("Poppins ExtraBold", 1, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Paket Silver");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(37, 37, 37))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(42, 97, 153));

        jLabel19.setBackground(new java.awt.Color(0, 50, 133));
        jLabel19.setFont(new java.awt.Font("Poppins ExtraBold", 1, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Paket Platinum");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        statusButton2.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        statusButton2.setForeground(new java.awt.Color(42, 97, 153));
        statusButton2.setText("Rp 10.000/kg");
        statusButton2.setAlignmentY(1.0F);
        statusButton2.setBorderPainted(false);
        statusButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton2ActionPerformed(evt);
            }
        });

        statusButton3.setBackground(new java.awt.Color(42, 98, 154));
        statusButton3.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        statusButton3.setForeground(new java.awt.Color(255, 255, 255));
        statusButton3.setText("Pesan");
        statusButton3.setAlignmentY(1.0F);
        statusButton3.setBorderPainted(false);
        statusButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton3ActionPerformed(evt);
            }
        });

        statusButton4.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton4.setForeground(new java.awt.Color(42, 97, 153));
        statusButton4.setText("Cuci Kering & Setrika");
        statusButton4.setAlignmentY(1.0F);
        statusButton4.setBorderPainted(false);
        statusButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton4ActionPerformed(evt);
            }
        });

        statusButton5.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton5.setForeground(new java.awt.Color(42, 97, 153));
        statusButton5.setText("Pengantaran Gratis");
        statusButton5.setAlignmentY(1.0F);
        statusButton5.setBorderPainted(false);
        statusButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton5ActionPerformed(evt);
            }
        });

        statusButton6.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton6.setForeground(new java.awt.Color(42, 97, 153));
        statusButton6.setText("Cuci Ekspress (1 Hari)");
        statusButton6.setAlignmentY(1.0F);
        statusButton6.setBorderPainted(false);
        statusButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton6ActionPerformed(evt);
            }
        });

        statusButton7.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton7.setForeground(new java.awt.Color(42, 97, 153));
        statusButton7.setText("Layanan VIP Prioritas");
        statusButton7.setAlignmentY(1.0F);
        statusButton7.setBorderPainted(false);
        statusButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton7ActionPerformed(evt);
            }
        });

        statusButton8.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton8.setForeground(new java.awt.Color(42, 97, 153));
        statusButton8.setText("V");
        statusButton8.setAlignmentY(1.0F);
        statusButton8.setBorderPainted(false);
        statusButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton8ActionPerformed(evt);
            }
        });

        statusButton9.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton9.setForeground(new java.awt.Color(42, 97, 153));
        statusButton9.setText("X");
        statusButton9.setAlignmentY(1.0F);
        statusButton9.setBorderPainted(false);
        statusButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton9ActionPerformed(evt);
            }
        });

        statusButton10.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton10.setForeground(new java.awt.Color(42, 97, 153));
        statusButton10.setText("X");
        statusButton10.setAlignmentY(1.0F);
        statusButton10.setBorderPainted(false);
        statusButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton10ActionPerformed(evt);
            }
        });

        statusButton11.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton11.setForeground(new java.awt.Color(42, 97, 153));
        statusButton11.setText("X");
        statusButton11.setAlignmentY(1.0F);
        statusButton11.setBorderPainted(false);
        statusButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(statusButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(statusButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(statusButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(statusButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(statusButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(statusButton2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(statusButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(statusButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        statusButton12.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        statusButton12.setForeground(new java.awt.Color(42, 97, 153));
        statusButton12.setText("Rp 20.000/kg");
        statusButton12.setAlignmentY(1.0F);
        statusButton12.setBorderPainted(false);
        statusButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton12ActionPerformed(evt);
            }
        });

        statusButton13.setBackground(new java.awt.Color(42, 98, 154));
        statusButton13.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        statusButton13.setForeground(new java.awt.Color(255, 255, 255));
        statusButton13.setText("Pesan");
        statusButton13.setAlignmentY(1.0F);
        statusButton13.setBorderPainted(false);
        statusButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton13ActionPerformed(evt);
            }
        });

        statusButton14.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton14.setForeground(new java.awt.Color(42, 97, 153));
        statusButton14.setText("Cuci Kering & Setrika");
        statusButton14.setAlignmentY(1.0F);
        statusButton14.setBorderPainted(false);
        statusButton14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton14ActionPerformed(evt);
            }
        });

        statusButton15.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton15.setForeground(new java.awt.Color(42, 97, 153));
        statusButton15.setText("Pengantaran Gratis");
        statusButton15.setAlignmentY(1.0F);
        statusButton15.setBorderPainted(false);
        statusButton15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton15ActionPerformed(evt);
            }
        });

        statusButton16.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton16.setForeground(new java.awt.Color(42, 97, 153));
        statusButton16.setText("Cuci Ekspress (1 Hari)");
        statusButton16.setAlignmentY(1.0F);
        statusButton16.setBorderPainted(false);
        statusButton16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton16ActionPerformed(evt);
            }
        });

        statusButton17.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton17.setForeground(new java.awt.Color(42, 97, 153));
        statusButton17.setText("Layanan VIP Prioritas");
        statusButton17.setAlignmentY(1.0F);
        statusButton17.setBorderPainted(false);
        statusButton17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton17ActionPerformed(evt);
            }
        });

        statusButton18.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton18.setForeground(new java.awt.Color(42, 97, 153));
        statusButton18.setText("V");
        statusButton18.setAlignmentY(1.0F);
        statusButton18.setBorderPainted(false);
        statusButton18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton18ActionPerformed(evt);
            }
        });

        statusButton19.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton19.setForeground(new java.awt.Color(42, 97, 153));
        statusButton19.setText("V");
        statusButton19.setAlignmentY(1.0F);
        statusButton19.setBorderPainted(false);
        statusButton19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton19ActionPerformed(evt);
            }
        });

        statusButton20.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton20.setForeground(new java.awt.Color(42, 97, 153));
        statusButton20.setText("V");
        statusButton20.setAlignmentY(1.0F);
        statusButton20.setBorderPainted(false);
        statusButton20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton20ActionPerformed(evt);
            }
        });

        statusButton21.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton21.setForeground(new java.awt.Color(42, 97, 153));
        statusButton21.setText("V");
        statusButton21.setAlignmentY(1.0F);
        statusButton21.setBorderPainted(false);
        statusButton21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(statusButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(statusButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(statusButton15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(statusButton14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(statusButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(statusButton12)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(statusButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(statusButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        statusButton32.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        statusButton32.setForeground(new java.awt.Color(42, 97, 153));
        statusButton32.setText("Rp 15.000/kg");
        statusButton32.setAlignmentY(1.0F);
        statusButton32.setBorderPainted(false);
        statusButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton32ActionPerformed(evt);
            }
        });

        statusButton33.setBackground(new java.awt.Color(42, 98, 154));
        statusButton33.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        statusButton33.setForeground(new java.awt.Color(255, 255, 255));
        statusButton33.setText("Pesan");
        statusButton33.setAlignmentY(1.0F);
        statusButton33.setBorderPainted(false);
        statusButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton33ActionPerformed(evt);
            }
        });

        statusButton34.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton34.setForeground(new java.awt.Color(42, 97, 153));
        statusButton34.setText("Cuci Kering & Setrika");
        statusButton34.setAlignmentY(1.0F);
        statusButton34.setBorderPainted(false);
        statusButton34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton34ActionPerformed(evt);
            }
        });

        statusButton35.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton35.setForeground(new java.awt.Color(42, 97, 153));
        statusButton35.setText("Pengantaran Gratis");
        statusButton35.setAlignmentY(1.0F);
        statusButton35.setBorderPainted(false);
        statusButton35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton35ActionPerformed(evt);
            }
        });

        statusButton36.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton36.setForeground(new java.awt.Color(42, 97, 153));
        statusButton36.setText("Cuci Ekspress (1 Hari)");
        statusButton36.setAlignmentY(1.0F);
        statusButton36.setBorderPainted(false);
        statusButton36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton36ActionPerformed(evt);
            }
        });

        statusButton37.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statusButton37.setForeground(new java.awt.Color(42, 97, 153));
        statusButton37.setText("Layanan VIP Prioritas");
        statusButton37.setAlignmentY(1.0F);
        statusButton37.setBorderPainted(false);
        statusButton37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton37ActionPerformed(evt);
            }
        });

        statusButton38.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton38.setForeground(new java.awt.Color(42, 97, 153));
        statusButton38.setText("V");
        statusButton38.setAlignmentY(1.0F);
        statusButton38.setBorderPainted(false);
        statusButton38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton38ActionPerformed(evt);
            }
        });

        statusButton39.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton39.setForeground(new java.awt.Color(42, 97, 153));
        statusButton39.setText("V");
        statusButton39.setAlignmentY(1.0F);
        statusButton39.setBorderPainted(false);
        statusButton39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton39ActionPerformed(evt);
            }
        });

        statusButton40.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton40.setForeground(new java.awt.Color(42, 97, 153));
        statusButton40.setText("V");
        statusButton40.setAlignmentY(1.0F);
        statusButton40.setBorderPainted(false);
        statusButton40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton40ActionPerformed(evt);
            }
        });

        statusButton41.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        statusButton41.setForeground(new java.awt.Color(42, 97, 153));
        statusButton41.setText("X");
        statusButton41.setAlignmentY(1.0F);
        statusButton41.setBorderPainted(false);
        statusButton41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton41ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusButton33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(statusButton36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(statusButton37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(statusButton35)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(statusButton34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(statusButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(statusButton32)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(statusButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(statusButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton1ActionPerformed

    private void riwayatButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatButton2ActionPerformed

    private void riwayatButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatButton1ActionPerformed

    private void riwayatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatButtonActionPerformed

    private void akunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akunButtonActionPerformed

    }//GEN-LAST:event_akunButtonActionPerformed

    private void statusButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton2ActionPerformed

    private void statusButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton3ActionPerformed

    private void statusButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton4ActionPerformed

    private void statusButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton5ActionPerformed

    private void statusButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton6ActionPerformed

    private void statusButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton7ActionPerformed

    private void statusButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton8ActionPerformed

    private void statusButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton9ActionPerformed

    private void statusButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton10ActionPerformed

    private void statusButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton11ActionPerformed

    private void statusButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton12ActionPerformed

    private void statusButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton13ActionPerformed

    private void statusButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton14ActionPerformed

    private void statusButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton15ActionPerformed

    private void statusButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton16ActionPerformed

    private void statusButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton17ActionPerformed

    private void statusButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton18ActionPerformed

    private void statusButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton19ActionPerformed

    private void statusButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton20ActionPerformed

    private void statusButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton21ActionPerformed

    private void statusButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton32ActionPerformed

    private void statusButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton33ActionPerformed

    private void statusButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton34ActionPerformed

    private void statusButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton35ActionPerformed

    private void statusButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton36ActionPerformed

    private void statusButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton37ActionPerformed

    private void statusButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton38ActionPerformed

    private void statusButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton39ActionPerformed

    private void statusButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton40ActionPerformed

    private void statusButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton41ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akunButton;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton riwayatButton;
    private javax.swing.JButton riwayatButton1;
    private javax.swing.JButton riwayatButton2;
    private javax.swing.JButton statusButton1;
    private javax.swing.JButton statusButton10;
    private javax.swing.JButton statusButton11;
    private javax.swing.JButton statusButton12;
    private javax.swing.JButton statusButton13;
    private javax.swing.JButton statusButton14;
    private javax.swing.JButton statusButton15;
    private javax.swing.JButton statusButton16;
    private javax.swing.JButton statusButton17;
    private javax.swing.JButton statusButton18;
    private javax.swing.JButton statusButton19;
    private javax.swing.JButton statusButton2;
    private javax.swing.JButton statusButton20;
    private javax.swing.JButton statusButton21;
    private javax.swing.JButton statusButton22;
    private javax.swing.JButton statusButton23;
    private javax.swing.JButton statusButton24;
    private javax.swing.JButton statusButton25;
    private javax.swing.JButton statusButton26;
    private javax.swing.JButton statusButton27;
    private javax.swing.JButton statusButton28;
    private javax.swing.JButton statusButton29;
    private javax.swing.JButton statusButton3;
    private javax.swing.JButton statusButton30;
    private javax.swing.JButton statusButton31;
    private javax.swing.JButton statusButton32;
    private javax.swing.JButton statusButton33;
    private javax.swing.JButton statusButton34;
    private javax.swing.JButton statusButton35;
    private javax.swing.JButton statusButton36;
    private javax.swing.JButton statusButton37;
    private javax.swing.JButton statusButton38;
    private javax.swing.JButton statusButton39;
    private javax.swing.JButton statusButton4;
    private javax.swing.JButton statusButton40;
    private javax.swing.JButton statusButton41;
    private javax.swing.JButton statusButton5;
    private javax.swing.JButton statusButton6;
    private javax.swing.JButton statusButton7;
    private javax.swing.JButton statusButton8;
    private javax.swing.JButton statusButton9;
    // End of variables declaration//GEN-END:variables
}
